spring:
  cloud:
    openfeign:
      client:
        config:
          default: # 'default' aplica a todos os clients
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

api:
  beneficios:
    url: http://localhost:8081/ejb/api/v1/beneficios
